single_instance: gravel

frontend:
  plugin: fltk
  config:
    layout:
      scale: 1.0
      max_hits: 6
      window_width: 800
      hit_title_height: 30
      hit_title_font_size: 20
      hit_subtitle_height: 20
      hit_subtitle_font_size: 12
      query_font_size: 25
      scrollbar_width: 10
      scrollbar_padding: 3
      padding: 8
    colors:
      background: 0x191a24
      accent: 0x189fcc
      text: 0xffffff
    behaviour:
      start_hidden: false
      auto_hide: false
      exit_on_hide: true
      auto_center_window: true
      show_scores: false

providers:
  - plugin: calculator
    subtitle: Copy to Clipboard

  - plugin: program

  - plugin: websearch

    ## https://github.com/thorio/gravel/tree/master/gravel-provider-websearch
    # config:
    #   ## Determines which URL is opened. The default is Google Search.
    #   ## The placeholder `{}` is replaced with the URL-encoded query.
    #   ##
    #   ## For example, you could use:
    #   ## - `https://duckduckgo.com/?q={}`
    #   ## - `https://www.ecosia.org/search?q={}`
    #   ## - `https://www.bing.com/search?q={}`
    #   ## - `https://search.yahoo.com/search?p={}`
    #   ##
    #   url_pattern: "https://www.google.com/search?q={}"
    #
    #   ## Changes the subtitle of the hit. Visual difference only.
    #   subtitle: Web Search

  - plugin: websearch
    keyword: tr
    config:
      url_pattern: "https://translate.google.com/?text={}"
      subtitle: Translate

  - plugin: system

    config:
      exit:
        title: exit
        subtitle: Exit gravel
      lock:
        title: lock
        subtitle: Lock the System
        command_linux: loginctl lock-session
      logout:
        title: log out
        subtitle: Close the current session
        command_linux: loginctl terminate-session $(loginctl session-status | awk 'NR==1{print $1}')
      restart:
        title: restart
        subtitle: Restart the System
        command_linux: shutdown -r now
      shutdown:
        title: shutdown
        subtitle: Shut the System down
        command_linux: shutdown now
      sleep:
        title: sleep
        subtitle: Put the System to sleep
        command_linux: systemctl suspend
  - plugin: kill
    keyword: kill
  - plugin: exec
    keyword: ">"
    config:
      subtitle: Run Command
